frr version 8.4_git
frr defaults traditional
hostname branch
no ipv6 forwarding
!
interface eth1
 ip address 192.168.11.2/30
exit
!
interface eth2
 ip address 192.168.12.2/30
exit
!
interface lo
 ip address 10.1.1.1/24
exit
!
router bgp 65001
 bgp router-id 10.1.1.1
 neighbor 192.168.11.1 remote-as 100
 neighbor 192.168.12.1 remote-as 200
 !
 address-family ipv4 unicast
  network 10.1.1.0/24
  neighbor 192.168.11.1 route-map RM_IN_ISP1 in
  neighbor 192.168.11.1 route-map RM_OUT out
  neighbor 192.168.12.1 route-map RM_IN in
  neighbor 192.168.12.1 route-map RM_OUT_ISP2 out
 exit-address-family
exit
!
ip prefix-list BRANCH_NET seq 5 permit 10.1.1.0/24
!
route-map RM_OUT permit 10
 match ip address prefix-list BRANCH_NET
exit
!
route-map RM_IN permit 10
exit
!
route-map RM_IN_ISP1 permit 10
 set local-preference 200
exit
!
route-map RM_OUT_ISP2 permit 10
 match ip address prefix-list BRANCH_NET
 set as-path prepend 65001 65001 65001
exit
