frr version 8.4_git
frr defaults traditional
hostname isp2
no ipv6 forwarding
!
interface eth1
 ip address 192.168.12.1/30
exit
!
interface eth2
 ip address 172.16.2.1/30
exit
!
router bgp 200
 bgp router-id 192.168.12.1
 no bgp ebgp-requires-policy
 neighbor 172.16.2.2 remote-as 888
 neighbor 192.168.12.2 remote-as 65001
exit
!
